# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_title', models.CharField(max_length=250)),
                ('game_description', models.CharField(max_length=500)),
                ('game_price', models.IntegerField()),
                ('game_highscore', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=250)),
                ('balance', models.IntegerField()),
                ('email', models.CharField(max_length=250)),
            ],
        ),
    ]
