# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-07 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0003_auto_20170107_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='price',
            field=models.FloatField(),
        ),
    ]
