# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-08 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0004_auto_20170107_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='highscore',
            field=models.IntegerField(default=0),
        ),
    ]
