# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-24 11:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0007_auto_20170123_1927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='producer',
            new_name='developer',
        ),
    ]
