# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-10 14:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gamestore', '0011_transaction'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gameplayer',
            unique_together=set([('game', 'user')]),
        ),
    ]
