# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-17 17:36
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0014_auto_20170217_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
